### ISSUE TITLE
Issues Regarding Milestone 2

### ISSUE THREAD

**Issue by AsenaKarolin** [bounswe/bounswe2020group1#339]
- [x] Price range shall be visible during filtering. 
- [x] Applying multiple filters at once shall be possible.
- [x] A user should not have to type his mailing adress again if an error occurs during the payment.
- [x] Rating should be enabled for different categories such as but not limited to: vendor, cargo, product.
- [x]  Log out option should be available on the sidebar. 
- [x]  Only strong passwords should be accepted by the system.
- [x]  Filtering should be moved to the left side of the page.

- [x]  More realistic data should be used for scenarios. 
- [x]  Typo in the order page shall be fixed.
- [x]  Warning messages shall be in English.
- [x]  The user shall not be able to enter anything else than positive numbers for stock and price fields.

**Comment by memetc** [comment]
- Filtering has moved to the right side of the page
- Multiple filters can be applied now.
- Price range values are displayed




![image](https://user-images.githubusercontent.com/33198811/103911539-3928b980-5117-11eb-93ee-c7a70747d28b.png)

**Comment by AsenaKarolin** [comment]
Typo and password strength is corrected in the frontend.

**Comment by yagizcolak** [comment]
Rating should be enabled for different categories such as but not limited to: vendor, cargo, product.
Customers are now able to rate both the product and the vendor. As a group decision, we discarded the idea of rating the cargo.

**Comment by barisalhan** [comment]
I think we can close this issue. As far as I know, we have resolved all of the items.
